# Generated by Django 2.2.24 on 2021-10-06 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aldryn_news', '0003_auto_20210803_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='latestnewsplugin',
            name='tags',
            field=models.ManyToManyField(blank=True, help_text='Show only the news tagged with chosen tags.', to='aldryn_news.Tag'),
        ),
    ]
