# Generated by Django 3.2.15 on 2022-09-28 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aldryn_news", "0004_auto_20211006_1440"),
    ]

    operations = [
        migrations.AddField(
            model_name="news",
            name="canonical_tag",
            field=models.URLField(blank=True),
        ),
    ]
